stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq curl libvulkan1 libxxf86vm-dev libosmesa6-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake git gcc gcc-multilib
  script:
    - rustc --version && cargo --version
    - cargo build --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq curl libvulkan1 libxxf86vm-dev libosmesa6-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake git gcc gcc-multilib
  script:
    - rustc --version && cargo --version
    - rustup component add rustfmt-preview --toolchain nightly
    - cargo fmt --all -- --check
    - cargo build --verbose
