unstable_features = true
comment_width = 100
condense_wildcard_suffixes = true
format_strings = true
imports_indent = "Block"
imports_layout = "Vertical"
max_width = 120
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 30
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
